name: user-management-system

services:

  # frontend:
  #   build: ./app
  #   ports:
  #     - "3000:80"

  server:
    build: ./api
    volumes:
      - ./api:/src/api:ro
    depends_on:
      - db
    restart: no

  nginx:
    image: nginx:stable-alpine3.23-perl
    volumes:
      - ./api:/src/api:ro
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: no
    depends_on:
      - server
    ports:
      - "8080:80"

  db:
    image: mysql:9.6
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: user_management_system
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/mysql
    restart: no
    ports:
      - "3306:3306"

volumes:
  db_data:
