name: user-management-system

services:
  server:
    image: php:8.4-fpm
    volumes:
      - ./server:/src/server:ro
    restart: no

  nginx:
    image: nginx:stable-alpine3.23-perl
    volumes:
      - ./server:/src/server:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: no
    depends_on:
      - server
    ports:
      - "8080:80"

  db:
    image: mysql:9.6
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: users
      MYSQL_USER: guest
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    restart: no
    ports:
      - "3306:3306"
