FROM php:8.4-fpm

RUN apt-get update \
    && apt-get install -y nginx \
    && docker-php-ext-install pdo pdo_mysql \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src/api

COPY . .

RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 10000

CMD ["sh", "-c", "php-fpm --nodaemonize & nginx -g 'daemon off;'"]
