FROM php:8.4-fpm

RUN apt-get update \
    && apt-get install -y nginx \
    && docker-php-ext-install pdo pdo_mysql \
    && rm -rf /var/lib/apt/lists/*

# RUN rm -f /etc/nginx/sites-enabled/default \
#     && rm -f /etc/nginx/sites-available/default

RUN sed -i 's/pm.max_children = 5/pm.max_children = 20/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm = dynamic/pm = static/g' /usr/local/etc/php-fpm.d/www.conf

WORKDIR /src/api

COPY . .

COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 10000

CMD ["sh", "-c", "php-fpm --nodaemonize && nginx -g 'daemon off;'"]
